name: Zelmux
options:
  bundleIdPrefix: com.cinetec.dev
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "2"
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG ZELMUX_DIAGNOSTICS"
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "ZELMUX_RELEASE"
packages:
  SwiftTerm:
    path: ThirdParty/SwiftTerm
targets:
  Zelmux:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Zelmux/Sources
    dependencies:
      - package: SwiftTerm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cinetec.dev.zelmux
        INFOPLIST_FILE: Zelmux/Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: E3LHDHQKAV
        TARGETED_DEVICE_FAMILY: "1,2"
  ZelmuxTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - ZelmuxTests
    dependencies:
      - package: SwiftTerm
      - target: Zelmux
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cinetec.dev.zelmux.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: E3LHDHQKAV
        TARGETED_DEVICE_FAMILY: "1,2"
